server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/cloudnote?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
  mvc:
    favicon:
      enabled: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.oracle.cloudnote.bean